POST http://localhost:4000/me
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODkwNDA5NzQsIm5iZiI6MTY4OTA0MDk3NCwiZXhwIjoxNjkwMjUwNTc0LCJpc3MiOiJTdXJyZWFsREIiLCJOUyI6InRlc3QiLCJEQiI6InRlc3QiLCJTQyI6ImFsbHVzZXJzIiwiSUQiOiJ1c2VyOnVwdWoweWlmeXoxMWlyeHZrd3djIn0.hnqwkgqTJ5X16hc89JWYex0epEecsROtvGsjGmg5FCD6nocgJP6PXgRRokRDwdi5OVQxWiQfmHxCZxieI4P0Bw",
    "username": "joonipea"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{

    "password": "12345693",
    "username": "tobie"
}

###
POST http://localhost:4000/signup
Content-Type: application/json

{
    "username": "tobie",
    "password": "12345693",
    "email": "tobie@joonipea.com",
    "settings": {
        "marketing": true
    }

}

###
POST http://localhost:4000/get
Content-Type: application/json

{
    "id": "recipe:black_eyed_peas"
}


###
POST http://localhost:4000/post
Content-Type: application/json

{
    "name": "Black Eyed Peas",
    "type": "recipe",
    "ingredients": [
        {
            "name": "Black Eyed Peas",
            "quantity": 1,
            "unit": "bunch",
            "type": "plant"
        },
        {
            "name": "Hammock",
            "quantity": 1,
            "unit": "kg",
            "type": "meat"
        },
        {
            "name": "Chicken Stock",
            "quantity": 1,
            "unit": "cup",
            "type": "recipe"
        },
        {
            "name": "Salt",
            "quantity": 1,
            "unit": "tsp",
            "type": "other"
        },
        {
            "name": "Pepper",
            "quantity": 1,
            "unit": "tsp",
            "type": "plant"
        },
        {
            "name": "Garlic",
            "quantity": 1,
            "unit": "clove",
            "type": "plant"
        },
        {
            "name": "Onion",
            "quantity": 2,
            "unit": "whole",
            "type": "plant"
        }
    ],
    "steps": [
        {
            "description": "Boil Hammock"
        },
        {
            "description": "Add Onions"
        },
        {
            "description": "Add Black Eyed Peas"
        }
    ]
}