PATCH http://localhost:4000/api/v1/update-user
Content-Type: application/json
Authentication: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODkyNjAwNDQsIm5iZiI6MTY4OTI2MDA0NCwiZXhwIjoxNjkwNDY5NjQ0LCJpc3MiOiJTdXJyZWFsREIiLCJOUyI6InRlc3QiLCJEQiI6InRlc3QiLCJTQyI6ImFsbHVzZXJzIiwiSUQiOiJ1c2VyOjhta2MzbTVrcDcyYXRhemZibm1hIn0.WADOjDrXjcT441VB0LzBmwCD7dRThH89fvY2A5krP-4CQR5fjNE3GK7gdQrd2Z_XGIrlp25jBkLoE7Q0AjKBXw

{
    "settings": {
        "marketing": true
    },
    "subscriptions": ["user:8mkc3m5kp72atazfbnma","user:di15aw9ca4kc73nh1buv"],
    "username": "joonipea"
}
###
GET http://localhost:4000/api/v1/user
Content-Type: application/javascript
x-rciad-requested-id: user:8mkc3m5kp72atazfbnma


###
GET http://localhost:4000/api/v1/me
Content-Type: application/json
Authentication: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA1MDg0MTQsIm5iZiI6MTY5MDUwODQxNCwiZXhwIjoxNjkxNzE4MDE0LCJpc3MiOiJTdXJyZWFsREIiLCJOUyI6InRlc3QiLCJEQiI6InRlc3QiLCJTQyI6ImFsbHVzZXJzIiwiSUQiOiJ1c2VyOjd3M2M5dHo1YXVudTV0cjFraGFzIn0.FAkOoHN9H7DNsDM5REGEidXbYLNi5l1DngV1vbvcVOWNAyM0V7_n5uUeHRXPYmTh98515_qTGnlKdjFE9nkHNQ



###
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{

    "password": "12345693",
    "username": "tobie"
}

###
POST http://localhost:4000/api/v1/signup
Content-Type: application/json

{
    "username": "tobie",
    "password": "12345693",
    "email": "tobie@joonipea.com",
    "settings": {
        "marketing": true
    }

}
###
DELETE http://localhost:4000/api/v1/delete
Content-Type: application/json
Authentication: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODkyNzY2MjksIm5iZiI6MTY4OTI3NjYyOSwiZXhwIjoxNjkwNDg2MjI5LCJpc3MiOiJTdXJyZWFsREIiLCJOUyI6InRlc3QiLCJEQiI6InRlc3QiLCJTQyI6ImFsbHVzZXJzIiwiSUQiOiJ1c2VyOmRpMTVhdzljYTRrYzczbmgxYnV2In0.xADqVQPxc4Z2fiNkgH1W0N-kJsILU9TVsJMGc7gkJt0cOPzD0PatQ9cmtK8Kv1GN5uN8hEkb5SHxg0pnXcnFKQ

{
    "id": "recipe:Chicken_Caesar_Salad"
}
###
GET http://localhost:4000/api/v1/get-relation
Content-Type: application/json
X-RCIAD-Requested-ID: plant:Garlic
x-rciad-requested-relation: made_of

###
GET http://localhost:4000/api/v1/get
X-RCIAD-Requested-ID: user:8mkc3m5kp72atazfbnma
x-rciad-page: 1
x-rciad-limit: 1
x-rciad-subscribed: user:8mkc3m5kp72atazfbnma,user:di15aw9ca4kc73nh1buv

###
GET http://localhost:4000/api/v1/get
X-RCIAD-Requested-ID: recipe
x-rciad-limit: 100

###
POST http://localhost:4000/api/v1/post
Content-Type: application/json
Authentication: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA5MDUzMzgsIm5iZiI6MTY5MDkwNTMzOCwiZXhwIjoxNjkyMTE0OTM4LCJpc3MiOiJTdXJyZWFsREIiLCJOUyI6InRlc3QiLCJEQiI6InRlc3QiLCJTQyI6ImFsbHVzZXJzIiwiSUQiOiJ1c2VyOmFzOTE0YXA1bGRjdXF6NG5zN2p2In0.bgoHuax5M5Et53PF35uukM6Q14CGpytyWUngtaICx4iIuX3aoJAhZqF30_RqbXz1qs8ogRQzRXo7ViSFKDrWKA

    {
  "name": "Gluten Free Vegan Chocolate Chip Cookies",
  "type": "recipe",
  "ingredient": [
    {
      "name": "Brown Sugar",
      "quantity": "1",
      "type": "ingredient",
      "unit": "cup"
    },
    {
      "name": "Coconut Oil",
      "quantity": "0.75",
      "type": "ingredient",
      "unit": "cup"
    },
    {
      "name": "Apple Sauce",
      "quantity": "0.5",
      "type": "ingredient",
      "unit": "cup"
    },
    {
      "name": "Vanilla Extract",
      "quantity": "2",
      "type": "ingredient",
      "unit": "tsp"
    },
    {
      "name": "Espresso Grounds",
      "quantity": "0.25",
      "type": "ingredient",
      "unit": "cup"
    },
    {
      "name": "Almond Flour",
      "quantity": "2.5",
      "type": "ingredient",
      "unit": "cup"
    },
    {
      "name": "Dark Chocolate",
      "quantity": "4",
      "type": "ingredient",
      "unit": "oz"
    },
    {
      "name": "Baking Powder",
      "quantity": "1",
      "type": "ingredient",
      "unit": "tsp"
    }
  ],
  "steps": [
    "Preheat oven to 350ºF.",
    "Mix coconut oil, brown sugar, apple sauce, and vanilla extract with a hand mixer.",
    "In a separate bowl, mix almond flour, espresso grounds, and baking powder.",
    "Fold the dry mixture into the wet mixture.",
    "Fold in the dark chocolate chips.",
    "Roll the dough into 1-inch balls and place them on a lined baking sheet.",
    "Bake for 8-10 minutes."
  ]
}


